# Change these first
owner: jpleasants # Your GitHub organization or username, where this repository lives
repo: plesk3 # The name of this repository
delay: 2000 # 2 seconds

sites:
  - name: Plesk 3
    url: https://plesk3.samitsolutions.com
    port: 8443
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Aexelar
    url: https://aexelar.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Bharat Grocery
    url: https://bharat-grocery.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Carolina Heart Center
    url: https://carolinaheartcenter.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Control Infotech
    url: https://control-infotech.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Durant Rd Pediatrics
    url: https://drpeds.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Coalition For Carolina Foundation
    url: https://coalitionforcarolinafoundation.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Crowdsourcing Sustainability
    url: https://crowdsourcingsustainability.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: KANORS EMR Forum
    url: https://forum.kanors-emr.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Fresh Indian Market
    url: https://freshindianmarket.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Harbor Hat
    url: https://harborhat.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: KANORS EMR Helpdesk
    url: https://helpdesk.kanors-emr.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Institrve
    url: https://institrve.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: KANORS EMR
    url: https://kanors-emr.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Khanna Sons Jewelers
    url: https://khannasonsjewelers.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: KANORS EMR Licensing
    url: https://licensing.kanors-emr.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Lj Neurology
    url: https://ljneurology.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Marizyme
    url: https://marizyme.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: My Medical Idea
    url: https://mymedicalidea.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Nazara NC
    url: https://nazaranc.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: peppernc
    url: https://peppernc.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Shah and Associated FP Portal
    url: https://portal.shahandassociatesfp.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Serge Tech Mechanical
    url: https://sergetechmechanical.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Shah and Associated FP
    url: https://shahandassociatesfp.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Shivji Photography
    url: https://shivji.photography
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Pickles And Play
    url: https://picklesandplay.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Sleep Clinic Of Ohio
    url: https://sleepclinicofohio.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Thepuppie
    url: https://thepuppie.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Stone ERP
    url: https://stone-erp.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: KANORS EMR Support
    url: https://support.kanors-emr.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: wfendo.com
    url: https://wfendo.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Zaykaunc Chapelhill
    url: https://zaykauncchapelhill.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Veear Projects
    url: https://veearprojects.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Vital Manage
    url: https://vitalmanage.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
 

    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /plesk3
  logoUrl: https://samitpublic.blob.core.windows.net/download/sam-it-dots(1).png
  name: SAM IT Solutions
  theme: night
  introTitle: "**Status** page highlighting active incidents, current status of endpoints, and historical data."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
