# Change these first
owner: jpleasants # Your GitHub organization or username, where this repository lives
repo: plesk3 # The name of this repository
delay: 2000 # 2 seconds

sites:
  - name: Plesk 3
    url: https://plesk3.samitsolutions.com
    port: 8443
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: Aexelar
    url: https://aexelar.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: shivji photography
    url: https://shivji.photography
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
   - name: Carolina Heart Center
    url: https://carolinaheartcenter.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: wfendo
    url: https://wfendo.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
   - name: veearprojects
    url: https://veearprojects.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: stone-erp
    url: https://stone-erp.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: nazaranc
    url: https://nazaranc.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: sergetechmechanical
    url: https://sergetechmechanical.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: vitalmanage
    url: https://vitalmanage.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: Harbor Hat
    url: https://harborhat.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: KANORS EMR
    url: https://kanors-emr.org
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: mymedicalidea
    url: https://mymedicalidea.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: KANORS EMR Helpdesk
    url: https://helpdesk.kanors-emr.org
    maxResponseTime: 15000
    expectedStatusCodes:
      - 200
      - 201
  - name: drpeds
    url: https://drpeds.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: KANORS EMR Licensing
    url: https://licensing.kanors-emr.org
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: institrve
    url: https://institrve.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: marizyme
    url: https://marizyme.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: Nazara NC
    url: https://nazaranc.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: khannasonsjewelers
    url: https://khannasonsjewelers.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: Shah and Associated FP Portal
    url: https://portal.shahandassociatesfp.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: Shah and Associated FP
    url: https://shahandassociatesfp.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: thepuppie
    url: https://thepuppie.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: peppernc
    url: https://peppernc.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: crowdsourcingsustainability
    url: https://crowdsourcingsustainability.org
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
  - name: zaykauncchapelhill
    url: https://zaykauncchapelhill.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: bharat grocery
    url: https://bharat-grocery.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: KANORS EMR Support
    url: https://support.kanors-emr.org
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: coalitionforcarolinafoundation
    url: https://coalitionforcarolinafoundation.org
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: tekrek
    url: https://tekrek.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: directedfacilitysolutions
    url: https://directedfacilitysolutions.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  - name: veearhealth
    url: https://veearhealth.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
  
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /plesk3
  logoUrl: https://samitpublic.blob.core.windows.net/download/sam-it-dots(1).png
  name: SAM IT Solutions
  theme: night
  introTitle: "**Status** page highlighting active incidents, current status of endpoints, and historical data."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
