# Change these first
owner: jpleasants # Your GitHub organization or username, where this repository lives
repo: plesk3 # The name of this repository

sites:
  - name: Plesk 3
    url: https://plesk3.samitsolutions.com
    port: 8443
  - name: Aexelar
    url: https://aexelar.com
  - name: Apex Food Service
    url: https://apexfoodservice.com
  - name: Carolina Heart Center
    url: https://carolinaheartcenter.com
  - name: Control Infotech
    url: https://control-infotech.com
  - name: Durant Rd Pediatrics
    url: https://drpeds.com
  - name: Dynpro
    url: https://dynpro.in
  - name: Dynpro India
    url: https://dynproindia.com
  - name: KANORS EMR Forum
    url: https://forum.kanors-emr.org
  - name: Fresh Indian Market
    url: https://freshindianmarket.com
  - name: Harbor Hat
    url: https://harborhat.com
  - name: KANORS EMR Helpdesk
    url: https://helpdesk.kanors-emr.org
  - name: Institrve
    url: https://institrve.com
  - name: Kanlo Net
    url: https://kanlo.net
  - name: KANORS EMR
    url: https://kanors-emr.org
  - name: Khanna Sons Jewelers
    url: https://khannasonsjewelers.com
  - name: KANORS EMR Licensing
    url: https://licensing.kanors-emr.org
  - name: Lj Neurology
    url: https://ljneurology.com
  - name: Marizyme
    url: https://marizyme.com
  - name: My Medical Idea
    url: https://mymedicalidea.com
  - name: Nazara NC
    url: https://nazaranc.com
  - name: Patty4 Morrisville
    url: https://patty4morrisville.com
  - name: Shah and Associated FP Portal
    url: https://portal.shahandassociatesfp.com
  - name: Serge Tech Mechanical
    url: https://sergetechmechanical.com
  - name: Shah and Associated FP
    url: https://shahandassociatesfp.com
  - name: Shivji Photography
    url: https://shivji.photography
  - name: Sizzlin Stir Fry
    url: https://sizzlinstirfry.com
  - name: Sleep Clinic Of Ohio
    url: https://sleepclinicofohio.com
  - name: Peoples Medical Care Staging
    url: https://staging.peoplesmedicalcare.org
  - name: Stone ERP
    url: https://stone-erp.com
  - name: KANORS EMR Support
    url: https://support.kanors-emr.org
  - name: Teampro India
    url: https://Teamproindia.com
  - name: Thought Leader Select
    url: https://thoughtleaderselect.com
  - name: Tnt Discount
    url: https://tntdiscount.city
  - name: Veear Projects
    url: https://veearprojects.com
  - name: Vital Manage
    url: https://vitalmanage.com
  - name: Wake Forest Endoscopy
    url: https://wfendo.com

    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /plesk3
  logoUrl: https://samitpublic.blob.core.windows.net/download/sam-it-dots(1).png
  name: SAM IT Solutions
  theme: night
  introTitle: "**Status** page highlighting active incidents, current status of endpoints, and historical data."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
